### ISSUE TITLE
[severe security issue] player can cause lua to run arbitrary code because of unprotected loadstring call

### ISSUE THREAD

**Issue by SumianVoice** [Bituvo/digilines_fpu#1]
https://github.com/Bituvo/digilines_fpu/blob/main/init.lua#L3

This allows the user to run any code, since loadstring will run any lua sent to it, meaning you could shut down the server or ban everyone, delete the world etc.

**Comment by Bituvo** [comment]
[Did you read line two?](https://github.com/Bituvo/digilines_fpu/blob/main/init.lua#L2)

This if statement only calls `loadstring` if the expression contains digits, operators, or parentheses. You cannot use it with letters. Therefore, it is safe from the dreaded sandbox escape.
